services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/node/.ssh

      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - app-network
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    env_file: ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      #  MONGO_INITDB_DATABASE: your-database-here
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    #    command: ["redis-server", "--appendonly", "yes"]

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
  redis_data:
